services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "8084:80"
      - "8085:8080"
      - "2224:22"
    depends_on:
      - mysql
    restart: unless-stopped

  web_load_balancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_load_balancer
    ports:
      - "8090:80"
      - "2225:22"
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: Anchhy-db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    ports:
      - "8091:80" # Binds to 0.0.0.0 by default, allowing remote access
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Hello@123
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
